## Settings
title: Lousy Blog
owner: "r3m4g"
url: "https://r3m4g.github.io"
baseurl: "/site"
permalink: /:title/
description: "Just Another Lousy Blog"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "z3k3.1024@gmail.com"
github: "r3m4g/site"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets"
statement: "Designed by DeerRIDER, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
